### ISSUE TITLE
.repos file for rolling does not contain updated tags/branch names for vcs import

### ISSUE THREAD

**Issue by jaiswalharsh** [UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation#15]
```
repositories:
  ign_ros2_control:
    type: git
    url: https://github.com/ignitionrobotics/ign_ros2_control.git
    version: main

  ros2_control_demos:
    type: git
    url: https://github.com/ros-controls/ros2_control_demos.git
    version: master

  Universal_Robots_Client_Library:
    type: git
    url: https://github.com/UniversalRobots/Universal_Robots_Client_Library.git
    version: master
  Universal_Robots_ROS2_Description:
    type: git
    url: https://github.com/UniversalRobots/Universal_Robots_ROS2_Description.git
    version: ros2
  Universal_Robots_ROS2_Driver:
    type: git
    url: https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver.git
    version: remove-description-package
  ur_msgs:
    type: git
    url: https://github.com/destogl/ur_msgs.git
    version: ros2
 ```
 
 The above when run gives the error as follows:
 ```
 -> vcs import src --input src/Universal_Robots_ROS2_Ignition_Simulation/Universal_Robots_ROS2_Ignition_Simulation.rolling.repos
E.EEE....E
=== src/Universal_Robots_Client_Library (git) ===

Already on 'master'
Your branch is up to date with 'origin/master'.
=== src/Universal_Robots_ROS2_Description (git) ===
Could not checkout ref 'simulation': fatal: invalid reference: simulation
=== src/Universal_Robots_ROS2_Driver (git) ===
Could not checkout ref 'remove-description-package': fatal: invalid reference: remove-description-package
=== src/ign_ros2_control (git) ===
Could not checkout ref 'main': fatal: invalid reference: main
=== src/moveit2 (git) ===
Could not checkout ref 'fix-controller-check-for-simulation': fatal: invalid reference: fix-controller-check-for-simulation
=== src/ros2_control (git) ===

Already on 'master'
Your branch is up to date with 'origin/master'.
=== src/ros2_control_demos (git) ===

Already on 'master'
Your branch is up to date with 'origin/master'.
=== src/ros2_controllers (git) ===

Already on 'master'
Your branch is up to date with 'origin/master'.
=== src/ros_ign (git) ===

Already on 'ros2'
Your branch is up to date with 'origin/ros2'.
=== src/ur_msgs (git) ===
Could not checkout ref 'ros2': fatal: invalid reference: ros2

```
