### ISSUE TITLE
force_torque_sensor_broadcaster values are not available

### ISSUE THREAD

**Issue by jaronski** [UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation#30]
i tried to look into the force torque sensor simulation.
i couldn't find the ur_controller/force_torque_sensor_broadcaster as stated in the config.yaml
i downloaded the description and driver pkg from universal robots.

Is there a functional launch example where the force torque sensor broadcaster is utilized and actually publishes the values of the force_torque_sensor from ignition gazebo fortress to ros2 as a geometric wrench msg?

Thanks for any help with the error:
`[ign-1] [ERROR] [1717421068.852962020] [controller_manager]: Can't activate controller 'ftsensor_broadcaster': State interface with key 'ft_sensor/force.x' does not exist`

i am using the force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster and not the ur_controller/... as i didn't find it in the repos

```
controller_manager:
  ros_parameters:
  update_rate: 100
  publish_rate: 100
  use_sim_time: True
  ftsensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

/ftsensor_broadcaster:
  ros__parameters:
    interface_names:
      force:
        x: ft_sensor/force.x
        y: ft_sensor/force.y
        z: ft_sensor/force.z 
      torque:
        x: ft_torque_sensor/torque.x
        y: ft_torque_sensor/torque.y
        z: ft_torque_sensor/torque.z
    
    frame_id: ft_sensor_link
    topic_name: ft_data

```
    
here is the part of the relevant urdf description:
   
```
    <joint name="ft_sensor_joint" type="fixed">
      <parent link="link_6_clean"/>
      <child link="ft_sensor_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <gazebo>
        <provideFeedback>true</provideFeedback>
      </gazebo>
    </joint>

    <ros2_control name="force_torque_sensor" type="sensor">
    <hardware>
      <plugin>force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster</plugin>
    </hardware>
    
    <sensor name="ft_sensor">
      <state_interface name="force.x"/>
      <state_interface name="force.y"/>
      <state_interface name="force.z"/>
      <state_interface name="torque.x"/>
      <state_interface name="torque.y"/>
      <state_interface name="torque.z"/>
      <param name="frame_id">sensor_frame</param>
    </sensor>
  </ros2_control>
```
  
  Thanks for any hints or tips
